/**
 * `GET /api/v1/ping` — the only M0 business-free orchestrator endpoint (see
 * docs/PLAN.md and ADR-0006). Hand-written response type; replace with a type
 * generated by openapi-typescript once the orchestrator publishes real endpoints
 * and an OpenAPI spec (M3/M5 — see CLAUDE.md web conventions).
 */
export interface PingResponse {
  service: string;
  dbTime: string;
  traceId: string | null;
}

export async function fetchPing(): Promise<PingResponse> {
  const response = await fetch("/api/v1/ping");
  if (!response.ok) {
    throw new Error(`GET /api/v1/ping failed: ${String(response.status)} ${response.statusText}`);
  }
  return (await response.json()) as PingResponse;
}
