/**
 * Orchestrator API types: aliases of the schemas generated by `openapi-typescript` from the
 * checked-in contract (`docs/api/orchestrator.openapi.json`, regenerate with `pnpm gen:api`,
 * verify with `pnpm gen:api --check`). Callers import types from here only. The run-event union
 * (SSE) is not in OpenAPI and stays hand-written in `run-events.ts`.
 */
import type { components } from "@/lib/api/generated/orchestrator";

type Schemas = components["schemas"];

export type Money = Schemas["Money"];
export type Report = Schemas["Report"];
export type RunCost = Schemas["RunCost"];
export type PingResponse = Schemas["PingResponse"];
export type StartRunRequest = Schemas["StartRunRequest"];
export type StartRunResponse = Schemas["StartRunResponse"];
export type RunSummary = Schemas["RunSummary"];
export type RunStatus = Schemas["RunSummary"]["status"];
export type RunListItem = Schemas["RunListItem"];
export type RunPage = Schemas["RunPage"];
export type RunPayments = Schemas["RunPayments"];
export type RunPaymentItem = Schemas["RunPaymentItem"];
export type PaymentIntentStatus = RunPaymentItem["status"];
export type ApprovalView = Schemas["ApprovalView"];
export type ApprovalResponse = Schemas["ApprovalResponse"];
export type DecisionRequest = Schemas["DecisionRequest"];
export type SpendOverview = Schemas["SpendOverview"];
export type SpendLimits = Schemas["SpendLimits"];
export type SpendByTool = Schemas["SpendByTool"];
export type ProblemDetail = Schemas["ProblemDetail"];

export function isTerminalStatus(status: RunStatus): boolean {
  return status === "SUCCEEDED" || status === "FAILED";
}
