/**
 * Orchestrator API types: aliases of the schemas generated by `openapi-typescript` from the
 * checked-in contract (`docs/api/orchestrator.openapi.json`, regenerate with `pnpm gen:api`,
 * verify with `pnpm gen:api --check`). Callers import types from here only. The run-event union
 * (SSE) is not in OpenAPI and stays hand-written in `run-events.ts`.
 */
import type { components } from "@/lib/api/generated/orchestrator";

import type { components as LedgerComponents } from "@/lib/api/generated/ledger";

type Schemas = components["schemas"];

export type Money = Schemas["Money"];
export type Report = Schemas["Report"];
export type RunCost = Schemas["RunCost"];
export type PingResponse = Schemas["PingResponse"];
export type StartRunRequest = Schemas["StartRunRequest"];
export type StartRunResponse = Schemas["StartRunResponse"];
export type RunSummary = Schemas["RunSummary"];
export type RunStatus = Schemas["RunSummary"]["status"];
export type RunListItem = Schemas["RunListItem"];
export type RunPage = Schemas["RunPage"];
export type RunPayments = Schemas["RunPayments"];
export type RunPaymentItem = Schemas["RunPaymentItem"];
export type PaymentIntentStatus = RunPaymentItem["status"];
export type ApprovalView = Schemas["ApprovalView"];
export type ApprovalResponse = Schemas["ApprovalResponse"];
export type DecisionRequest = Schemas["DecisionRequest"];
export type SpendOverview = Schemas["SpendOverview"];
export type SpendLimits = Schemas["SpendLimits"];
export type SpendByTool = Schemas["SpendByTool"];
export type ProblemDetail = Schemas["ProblemDetail"];

// Ledger API (docs/api/ledger.openapi.json). `Money` and `ProblemDetail` stay the orchestrator's:
// the shapes are identical and screens use one name.
type LedgerSchemas = LedgerComponents["schemas"];

export type TrialBalanceRow = LedgerSchemas["TrialBalanceRow"];
export type PaymentSummary = LedgerSchemas["PaymentSummary"];
export type PaymentPage = LedgerSchemas["PaymentPage"];
export type PaymentDetail = LedgerSchemas["PaymentDetail"];
export type PaymentEntry = LedgerSchemas["PaymentEntry"];
export type PaymentPosting = LedgerSchemas["PaymentPosting"];
export type PaymentFinding = LedgerSchemas["PaymentFinding"];
export type RevenueReport = LedgerSchemas["RevenueReport"];
export type SellerRevenue = LedgerSchemas["SellerRevenue"];
export type SignedAmount = LedgerSchemas["SignedAmount"];
export type ReconciliationReport = LedgerSchemas["ReconciliationReport"];
export type ReconciliationItem = LedgerSchemas["ReconciliationItem"];
export type ReconciliationCounters = LedgerSchemas["ReconciliationCounters"];
export type ReconciliationRunList = LedgerSchemas["ReconciliationRunList"];
export type ReconciliationRunSummary = LedgerSchemas["ReconciliationRunSummary"];
export type ReconciliationStarted = LedgerSchemas["ReconciliationStarted"];
export type LedgerBook = "BUYER" | "SELLER";

export function isTerminalStatus(status: RunStatus): boolean {
  return status === "SUCCEEDED" || status === "FAILED";
}
