package io.github.orhanyarkin.saiman.orchestrator.tool;

import java.util.List;

/**
 * What a model is told about one tool: its name, a fixed description and the JSON schema of its
 * input, generated by code from {@link ToolParameter}s (so it can only ever list {@code ticker} and
 * {@code question}).
 */
public record ToolDefinition(String name, String description, List<ToolParameter> parameters, String inputSchema) {

    public ToolDefinition {
        parameters = List.copyOf(parameters);
    }

    static ToolDefinition of(ResearchTool tool) {
        return new ToolDefinition(tool.name(), tool.description(), tool.parameters(), schema(tool.parameters()));
    }

    private static String schema(List<ToolParameter> parameters) {
        StringBuilder properties = new StringBuilder();
        StringBuilder required = new StringBuilder();
        for (ToolParameter parameter : parameters) {
            if (!properties.isEmpty()) {
                properties.append(',');
                required.append(',');
            }
            properties.append('"').append(parameter.jsonName()).append("\":{\"type\":\"string\",\"description\":\"");
            properties.append(parameter.description()).append('"');
            switch (parameter) {
                case TICKER -> properties.append(",\"pattern\":\"^[A-Z0-9]{3,6}$\"");
                case QUESTION ->
                    properties
                            .append(",\"minLength\":")
                            .append(UntrustedText.MIN_QUESTION)
                            .append(",\"maxLength\":")
                            .append(UntrustedText.MAX_QUESTION);
            }
            properties.append('}');
            required.append('"').append(parameter.jsonName()).append('"');
        }
        return "{\"type\":\"object\",\"properties\":{" + properties + "},\"required\":[" + required
                + "],\"additionalProperties\":false}";
    }
}
