import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config([
  {
    // src/routeTree.gen.ts is generated by @tanstack/router-plugin's Vite plugin, on every
    // `pnpm dev` or `pnpm build` run. It must still be committed: `pnpm build` runs `tsc -b`
    // before `vite build`, so a fresh clone would fail to typecheck without it already present.
    // Never hand-edited or linted (it also self-excludes via its own generated header).
    ignores: [
      "dist",
      "src/routeTree.gen.ts",
      "src/lib/api/generated",
      "playwright-report",
      "reports",
      "test-results",
    ],
  },
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.strictTypeChecked,
      tseslint.configs.stylisticTypeChecked,
      reactHooks.configs.flat["recommended-latest"],
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2023,
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    // ADR-0023: the API token lives in memory (optionally sessionStorage for the tab), never in
    // localStorage, which survives the tab and is shared by every script on the origin.
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-globals": [
        "error",
        { name: "localStorage", message: "Never persist the API token: see ADR-0023." },
      ],
      "no-restricted-properties": [
        "error",
        ...["window", "globalThis", "self", "top", "parent"].map((object) => ({
          object,
          property: "localStorage",
          message: "Never persist the API token: see ADR-0023.",
        })),
      ],
      "no-restricted-syntax": [
        "error",
        {
          selector: "MemberExpression[computed=true][property.value='localStorage']",
          message: "Never persist the API token: see ADR-0023.",
        },
        {
          selector: "Identifier[name='localStorage']",
          message: "Never persist the API token: see ADR-0023.",
        },
      ],
    },
  },
  {
    // shadcn/ui convention: these files export a component plus its cva() variants function
    // (e.g. `buttonVariants`) from the same module. That's intentional, not a fast-refresh bug.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  {
    // TanStack Router file-based routes only ever export a `Route` object, which
    // eslint-plugin-react-refresh doesn't recognise as a component-shaped export.
    files: ["src/routes/**/*.{ts,tsx}"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
]);
